name: Validate AWS Deployments
description: Validate AWS deployments using Open Policy Agent (OPA) and Terraform plan files.
author: André Buchmann

inputs:
  tfplan_path:
    description: Path to the Terraform plan in JSON format.
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Setup OPA
      uses: open-policy-agent/setup-opa@v2
      with:
        version: 1.3.0

    - name: Validate AWS Deployment
      run: |
        result=$(opa exec --decision terraform --bundle "$(dirname "$0")/policy" ${{ inputs.tfplan_path }} | jq '.result[0].result')
        allow=$(echo "$result" | jq -r '.allow')
        violations=$(echo "$result" | jq -r '.violations')
        if [ "$allow" != "true" ]; then
          echo "❌ Policy check failed: $violations"
          exit 1
        else
          echo "✅ Your terraform plan has no violations. Keep being awesome!" 
        fi
      shell: bash