name: Run AWS Validation checks

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Run AWS validation
        uses: androzo/aws-validation@main
        with:
          tfplan_path: tfplan.json